export type Difficulty = "Easy" | "Medium" | "Hard";
export type ProblemStatus = "not-started" | "in-progress" | "solved";

export type DsaProblem = {
  id: number;
  title: string;
  difficulty: Difficulty;
  description: string;
  topics: string[];
  url: string;
};

export const arrayProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Two Sum",
    difficulty: "Easy",
    description: "Find two numbers in an array that add up to a target value.",
    topics: ["Array", "Hash Table"],
    url: "https://leetcode.com/problems/two-sum/",
  },
  {
    id: 2,
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    description: "Find the maximum profit from buying and selling a stock once.",
    topics: ["Array", "Greedy"],
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  },
  {
    id: 3,
    title: "Maximum Subarray",
    difficulty: "Medium",
    description: "Find the contiguous subarray with the largest sum.",
    topics: ["Array", "Divide and Conquer", "Dynamic Programming"],
    url: "https://leetcode.com/problems/maximum-subarray/",
  },
  {
    id: 4,
    title: "Product of Array Except Self",
    difficulty: "Medium",
    description: "Return an array where each element is the product of all other elements.",
    topics: ["Array", "Prefix Sum"],
    url: "https://leetcode.com/problems/product-of-array-except-self/",
  },
  {
    id: 5,
    title: "Contains Duplicate",
    difficulty: "Easy",
    description: "Determine whether any value appears at least twice in an array.",
    topics: ["Array", "Hash Table"],
    url: "https://leetcode.com/problems/contains-duplicate/",
  },
  {
    id: 6,
    title: "Maximum Product Subarray",
    difficulty: "Medium",
    description: "Find the contiguous subarray with the largest product.",
    topics: ["Array", "Dynamic Programming"],
    url: "https://leetcode.com/problems/maximum-product-subarray/",
  },
  {
    id: 7,
    title: "Move Zeroes",
    difficulty: "Easy",
    description:
      "Move all zeroes to the end of the array while maintaining the order of non-zero elements.",
    topics: ["Array", "Two Pointers"],
    url: "https://leetcode.com/problems/move-zeroes/",
  },
  {
    id: 8,
    title: "Rotate Array",
    difficulty: "Medium",
    description: "Rotate the array to the right by k steps.",
    topics: ["Array", "Math", "Two Pointers"],
    url: "https://leetcode.com/problems/rotate-array/",
  },
  {
    id: 9,
    title: "Valid Anagram",
    difficulty: "Easy",
    description: "Determine whether two strings are anagrams of each other.",
    topics: ["Hash Table", "String", "Sorting"],
    url: "https://leetcode.com/problems/valid-anagram/",
  },
  {
    id: 10,
    title: "Intersection of Two Arrays",
    difficulty: "Easy",
    description: "Return the unique elements that appear in both arrays.",
    topics: ["Array", "Hash Table", "Two Pointers"],
    url: "https://leetcode.com/problems/intersection-of-two-arrays/",
  },
  {
    id: 11,
    title: "Majority Element",
    difficulty: "Easy",
    description: "Find the element that appears more than half of the time in the array.",
    topics: ["Array", "Hash Table", "Sorting"],
    url: "https://leetcode.com/problems/majority-element/",
  },
  {
    id: 12,
    title: "Merge Sorted Array",
    difficulty: "Easy",
    description: "Merge two sorted arrays into the first array in sorted order.",
    topics: ["Array", "Two Pointers", "Sorting"],
    url: "https://leetcode.com/problems/merge-sorted-array/",
  },
  {
    id: 13,
    title: "3Sum",
    difficulty: "Medium",
    description: "Find all unique triplets in the array that add up to zero.",
    topics: ["Array", "Two Pointers", "Sorting"],
    url: "https://leetcode.com/problems/3sum/",
  },
  {
    id: 14,
    title: "Container With Most Water",
    difficulty: "Medium",
    description:
      "Find two lines that together with the x-axis form a container holding the most water.",
    topics: ["Array", "Two Pointers", "Greedy"],
    url: "https://leetcode.com/problems/container-with-most-water/",
  },
  {
    id: 15,
    title: "Subarray Sum Equals K",
    difficulty: "Medium",
    description: "Count the number of subarrays whose sum equals k.",
    topics: ["Array", "Hash Table", "Prefix Sum"],
    url: "https://leetcode.com/problems/subarray-sum-equals-k/",
  },
  {
    id: 16,
    title: "Trapping Rain Water",
    difficulty: "Hard",
    description:
      "Calculate how much rainwater can be trapped between the bars of an elevation map.",
    topics: ["Array", "Two Pointers", "Dynamic Programming", "Stack"],
    url: "https://leetcode.com/problems/trapping-rain-water/",
  },
  {
    id: 17,
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    description: "Find the k most frequently occurring elements in an array.",
    topics: ["Array", "Hash Table", "Heap", "Sorting", "Bucket Sort"],
    url: "https://leetcode.com/problems/top-k-frequent-elements/",
  },
  {
    id: 18,
    title: "Valid Sudoku",
    difficulty: "Medium",
    description: "Determine whether a 9x9 Sudoku board is valid.",
    topics: ["Array", "Hash Table", "Matrix"],
    url: "https://leetcode.com/problems/valid-sudoku/",
  },
  {
    id: 19,
    title: "Longest Consecutive Sequence",
    difficulty: "Medium",
    description: "Find the length of the longest sequence of consecutive integers in an array.",
    topics: ["Array", "Hash Table", "Union Find"],
    url: "https://leetcode.com/problems/longest-consecutive-sequence/",
  },
];

export const binarySearchProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Binary Search",
    difficulty: "Easy",
    description: "Search for a target value in a sorted array.",
    topics: ["Array", "Binary Search"],
    url: "https://leetcode.com/problems/binary-search/",
  },
  {
    id: 2,
    title: "Search Insert Position",
    difficulty: "Easy",
    description: "Find the index where a target should be inserted in a sorted array.",
    topics: ["Array", "Binary Search"],
    url: "https://leetcode.com/problems/search-insert-position/",
  },
  {
    id: 3,
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    description: "Search for a target in a rotated sorted array.",
    topics: ["Array", "Binary Search"],
    url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
  },
  {
    id: 4,
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: "Medium",
    description: "Find the minimum element in a rotated sorted array.",
    topics: ["Array", "Binary Search"],
    url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
  },
  {
    id: 5,
    title: "Find Peak Element",
    difficulty: "Medium",
    description: "Find a peak element in an array using binary search.",
    topics: ["Array", "Binary Search"],
    url: "https://leetcode.com/problems/find-peak-element/",
  },
  {
    id: 6,
    title: "Koko Eating Bananas",
    difficulty: "Medium",
    description:
      "Find the minimum eating speed needed to finish all bananas within the given hours.",
    topics: ["Binary Search", "Greedy"],
    url: "https://leetcode.com/problems/koko-eating-bananas/",
  },
  {
    id: 7,
    title: "Capacity To Ship Packages Within D Days",
    difficulty: "Medium",
    description:
      "Find the minimum ship capacity needed to deliver all packages within the given number of days.",
    topics: ["Binary Search", "Greedy"],
    url: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/",
  },
  {
    id: 8,
    title: "Search a 2D Matrix",
    difficulty: "Medium",
    description: "Search for a target value in an m x n matrix with sorted rows and columns.",
    topics: ["Array", "Binary Search", "Matrix"],
    url: "https://leetcode.com/problems/search-a-2d-matrix/",
  },
  {
    id: 9,
    title: "Time Based Key-Value Store",
    difficulty: "Medium",
    description: "Design a time-based key-value store supporting set and get by timestamp.",
    topics: ["Hash Table", "String", "Binary Search", "Design"],
    url: "https://leetcode.com/problems/time-based-key-value-store/",
  },
  {
    id: 10,
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    description: "Find the median of two sorted arrays in logarithmic time.",
    topics: ["Array", "Binary Search", "Divide and Conquer"],
    url: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
  },
];

export const stringProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Valid Anagram",
    difficulty: "Easy",
    description: "Determine whether two strings are anagrams of each other.",
    topics: ["Hash Table", "String", "Sorting"],
    url: "https://leetcode.com/problems/valid-anagram/",
  },
  {
    id: 2,
    title: "Valid Palindrome",
    difficulty: "Easy",
    description:
      "Determine whether a string reads the same forward and backward after ignoring non-alphanumeric characters.",
    topics: ["String", "Two Pointers"],
    url: "https://leetcode.com/problems/valid-palindrome/",
  },
  {
    id: 3,
    title: "Longest Common Prefix",
    difficulty: "Easy",
    description: "Find the longest common prefix shared by all strings in an array.",
    topics: ["String"],
    url: "https://leetcode.com/problems/longest-common-prefix/",
  },
  {
    id: 4,
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    description: "Find the length of the longest substring without repeating characters.",
    topics: ["String", "Hash Table", "Sliding Window"],
    url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
  },
  {
    id: 5,
    title: "Group Anagrams",
    difficulty: "Medium",
    description: "Group strings that are anagrams of each other.",
    topics: ["String", "Hash Table", "Sorting"],
    url: "https://leetcode.com/problems/group-anagrams/",
  },
  {
    id: 6,
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    description: "Find the longest palindromic substring within a given string.",
    topics: ["String", "Dynamic Programming"],
    url: "https://leetcode.com/problems/longest-palindromic-substring/",
  },
  {
    id: 7,
    title: "Palindromic Substrings",
    difficulty: "Medium",
    description: "Count how many palindromic substrings exist in a given string.",
    topics: ["String", "Dynamic Programming"],
    url: "https://leetcode.com/problems/palindromic-substrings/",
  },
  {
    id: 8,
    title: "Encode and Decode Strings",
    difficulty: "Medium",
    description: "Design an algorithm to encode a list of strings into one string and decode it back.",
    topics: ["Array", "String", "Design"],
    url: "https://leetcode.com/problems/encode-and-decode-strings/",
  },
];

export const twoPointersProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Two Sum II - Input Array Is Sorted",
    difficulty: "Medium",
    description:
      "Find two numbers in a sorted array that add up to a target value, using O(1) extra space.",
    topics: ["Array", "Two Pointers", "Binary Search"],
    url: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
  },
];

export const stackProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Valid Parentheses",
    difficulty: "Easy",
    description: "Determine if a string of brackets is valid using a stack.",
    topics: ["String", "Stack"],
    url: "https://leetcode.com/problems/valid-parentheses/",
  },
  {
    id: 2,
    title: "Min Stack",
    difficulty: "Medium",
    description:
      "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.",
    topics: ["Stack", "Design"],
    url: "https://leetcode.com/problems/min-stack/",
  },
  {
    id: 3,
    title: "Evaluate Reverse Polish Notation",
    difficulty: "Medium",
    description: "Evaluate the value of an arithmetic expression in Reverse Polish Notation.",
    topics: ["Array", "Math", "Stack"],
    url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
  },
  {
    id: 4,
    title: "Generate Parentheses",
    difficulty: "Medium",
    description: "Generate all combinations of well-formed parentheses for n pairs.",
    topics: ["String", "Backtracking"],
    url: "https://leetcode.com/problems/generate-parentheses/",
  },
  {
    id: 5,
    title: "Daily Temperatures",
    difficulty: "Medium",
    description: "Find how many days until a warmer temperature for each day, using a monotonic stack.",
    topics: ["Array", "Stack", "Monotonic Stack"],
    url: "https://leetcode.com/problems/daily-temperatures/",
  },
  {
    id: 6,
    title: "Car Fleet",
    difficulty: "Medium",
    description: "Determine how many car fleets will arrive at the destination.",
    topics: ["Array", "Stack", "Sorting", "Monotonic Stack"],
    url: "https://leetcode.com/problems/car-fleet/",
  },
  {
    id: 7,
    title: "Largest Rectangle in Histogram",
    difficulty: "Hard",
    description: "Find the area of the largest rectangle that fits within a histogram.",
    topics: ["Array", "Stack", "Monotonic Stack"],
    url: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
  },
];

export const slidingWindowProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Longest Repeating Character Replacement",
    difficulty: "Medium",
    description: "Find the longest substring with the same letter after replacing at most k characters.",
    topics: ["String", "Hash Table", "Sliding Window"],
    url: "https://leetcode.com/problems/longest-repeating-character-replacement/",
  },
  {
    id: 2,
    title: "Permutation in String",
    difficulty: "Medium",
    description: "Determine whether a string contains a permutation of another string as a substring.",
    topics: ["String", "Hash Table", "Sliding Window"],
    url: "https://leetcode.com/problems/permutation-in-string/",
  },
  {
    id: 3,
    title: "Minimum Window Substring",
    difficulty: "Hard",
    description: "Find the smallest substring containing all characters of another string.",
    topics: ["String", "Hash Table", "Sliding Window"],
    url: "https://leetcode.com/problems/minimum-window-substring/",
  },
  {
    id: 4,
    title: "Sliding Window Maximum",
    difficulty: "Hard",
    description: "Find the maximum value in every sliding window of size k.",
    topics: ["Array", "Sliding Window", "Monotonic Queue", "Heap"],
    url: "https://leetcode.com/problems/sliding-window-maximum/",
  },
];

export const linkedListProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Reverse Linked List",
    difficulty: "Easy",
    description: "Reverse a singly linked list.",
    topics: ["Linked List", "Recursion"],
    url: "https://leetcode.com/problems/reverse-linked-list/",
  },
  {
    id: 2,
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    description: "Merge two sorted linked lists into one sorted list.",
    topics: ["Linked List", "Recursion"],
    url: "https://leetcode.com/problems/merge-two-sorted-lists/",
  },
  {
    id: 3,
    title: "Linked List Cycle",
    difficulty: "Easy",
    description: "Determine whether a linked list has a cycle using fast and slow pointers.",
    topics: ["Linked List", "Two Pointers"],
    url: "https://leetcode.com/problems/linked-list-cycle/",
  },
  {
    id: 4,
    title: "Reorder List",
    difficulty: "Medium",
    description: "Reorder a linked list by interleaving nodes from the front and back.",
    topics: ["Linked List", "Two Pointers", "Stack"],
    url: "https://leetcode.com/problems/reorder-list/",
  },
  {
    id: 5,
    title: "Remove Nth Node From End of List",
    difficulty: "Medium",
    description: "Remove the nth node from the end of a linked list in one pass.",
    topics: ["Linked List", "Two Pointers"],
    url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
  },
  {
    id: 6,
    title: "Copy List with Random Pointer",
    difficulty: "Medium",
    description: "Deep copy a linked list where each node has an extra random pointer.",
    topics: ["Hash Table", "Linked List"],
    url: "https://leetcode.com/problems/copy-list-with-random-pointer/",
  },
  {
    id: 7,
    title: "Add Two Numbers",
    difficulty: "Medium",
    description: "Add two numbers represented as linked lists of digits in reverse order.",
    topics: ["Linked List", "Math", "Recursion"],
    url: "https://leetcode.com/problems/add-two-numbers/",
  },
  {
    id: 8,
    title: "Find the Duplicate Number",
    difficulty: "Medium",
    description: "Find the duplicate number in an array using cycle detection.",
    topics: ["Array", "Two Pointers", "Binary Search", "Bit Manipulation"],
    url: "https://leetcode.com/problems/find-the-duplicate-number/",
  },
  {
    id: 9,
    title: "LRU Cache",
    difficulty: "Medium",
    description: "Design a least recently used (LRU) cache with O(1) get and put.",
    topics: ["Hash Table", "Linked List", "Design"],
    url: "https://leetcode.com/problems/lru-cache/",
  },
  {
    id: 10,
    title: "Merge k Sorted Lists",
    difficulty: "Hard",
    description: "Merge k sorted linked lists into one sorted list.",
    topics: ["Linked List", "Divide and Conquer", "Heap", "Merge Sort"],
    url: "https://leetcode.com/problems/merge-k-sorted-lists/",
  },
  {
    id: 11,
    title: "Reverse Nodes in k-Group",
    difficulty: "Hard",
    description: "Reverse the nodes of a linked list k at a time.",
    topics: ["Linked List", "Recursion"],
    url: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
  },
];

export const treeProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Invert Binary Tree",
    difficulty: "Easy",
    description: "Invert a binary tree by swapping every left and right child.",
    topics: ["Tree", "DFS", "BFS", "Binary Tree"],
    url: "https://leetcode.com/problems/invert-binary-tree/",
  },
  {
    id: 2,
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    description: "Find the maximum depth of a binary tree.",
    topics: ["Tree", "DFS", "BFS", "Binary Tree"],
    url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
  },
  {
    id: 3,
    title: "Diameter of Binary Tree",
    difficulty: "Easy",
    description: "Find the length of the longest path between any two nodes in a binary tree.",
    topics: ["Tree", "DFS", "Binary Tree"],
    url: "https://leetcode.com/problems/diameter-of-binary-tree/",
  },
  {
    id: 4,
    title: "Balanced Binary Tree",
    difficulty: "Easy",
    description: "Determine whether a binary tree is height-balanced.",
    topics: ["Tree", "DFS", "Binary Tree"],
    url: "https://leetcode.com/problems/balanced-binary-tree/",
  },
  {
    id: 5,
    title: "Same Tree",
    difficulty: "Easy",
    description: "Determine whether two binary trees are structurally identical with the same values.",
    topics: ["Tree", "DFS", "Binary Tree"],
    url: "https://leetcode.com/problems/same-tree/",
  },
  {
    id: 6,
    title: "Subtree of Another Tree",
    difficulty: "Easy",
    description: "Determine whether one binary tree is a subtree of another.",
    topics: ["Tree", "DFS", "Binary Tree", "String Matching"],
    url: "https://leetcode.com/problems/subtree-of-another-tree/",
  },
  {
    id: 7,
    title: "Lowest Common Ancestor of a BST",
    difficulty: "Medium",
    description: "Find the lowest common ancestor of two nodes in a binary search tree.",
    topics: ["Tree", "DFS", "Binary Search Tree", "Binary Tree"],
    url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
  },
  {
    id: 8,
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    description: "Return the level order traversal of a binary tree's node values.",
    topics: ["Tree", "BFS", "Binary Tree"],
    url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
  },
  {
    id: 9,
    title: "Binary Tree Right Side View",
    difficulty: "Medium",
    description: "Return the values visible from the right side of a binary tree.",
    topics: ["Tree", "DFS", "BFS", "Binary Tree"],
    url: "https://leetcode.com/problems/binary-tree-right-side-view/",
  },
  {
    id: 10,
    title: "Count Good Nodes in Binary Tree",
    difficulty: "Medium",
    description: "Count nodes where the path from the root has no node with a greater value.",
    topics: ["Tree", "DFS", "Binary Tree"],
    url: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
  },
  {
    id: 11,
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    description: "Determine whether a binary tree is a valid binary search tree.",
    topics: ["Tree", "DFS", "Binary Search Tree", "Binary Tree"],
    url: "https://leetcode.com/problems/validate-binary-search-tree/",
  },
  {
    id: 12,
    title: "Kth Smallest Element in a BST",
    difficulty: "Medium",
    description: "Find the kth smallest value in a binary search tree.",
    topics: ["Tree", "DFS", "Binary Search Tree", "Binary Tree"],
    url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
  },
  {
    id: 13,
    title: "Construct Binary Tree from Preorder and Inorder Traversal",
    difficulty: "Medium",
    description: "Rebuild a binary tree from its preorder and inorder traversals.",
    topics: ["Tree", "Array", "Hash Table", "Divide and Conquer", "Binary Tree"],
    url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
  },
  {
    id: 14,
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    description: "Find the maximum path sum between any two nodes in a binary tree.",
    topics: ["Tree", "DFS", "Dynamic Programming", "Binary Tree"],
    url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
  },
  {
    id: 15,
    title: "Serialize and Deserialize Binary Tree",
    difficulty: "Hard",
    description: "Design an algorithm to serialize and deserialize a binary tree.",
    topics: ["Tree", "DFS", "BFS", "Design", "String", "Binary Tree"],
    url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
  },
];

export const trieProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Implement Trie (Prefix Tree)",
    difficulty: "Medium",
    description: "Implement a trie with insert, search, and prefix search operations.",
    topics: ["Hash Table", "String", "Design", "Trie"],
    url: "https://leetcode.com/problems/implement-trie-prefix-tree/",
  },
  {
    id: 2,
    title: "Design Add and Search Words Data Structure",
    difficulty: "Medium",
    description: "Design a data structure that supports adding words and searching with wildcards.",
    topics: ["String", "Depth-First Search", "Design", "Trie"],
    url: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
  },
  {
    id: 3,
    title: "Word Search II",
    difficulty: "Hard",
    description: "Find all words from a list that can be formed in a grid of letters.",
    topics: ["Array", "String", "Backtracking", "Trie", "Matrix"],
    url: "https://leetcode.com/problems/word-search-ii/",
  },
];

export const heapProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Kth Largest Element in a Stream",
    difficulty: "Easy",
    description: "Design a class that finds the kth largest element in a growing stream of numbers.",
    topics: ["Tree", "Design", "Heap", "Binary Search Tree", "Data Stream"],
    url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
  },
  {
    id: 2,
    title: "Last Stone Weight",
    difficulty: "Easy",
    description: "Repeatedly smash the two heaviest stones together until at most one remains.",
    topics: ["Array", "Heap"],
    url: "https://leetcode.com/problems/last-stone-weight/",
  },
  {
    id: 3,
    title: "K Closest Points to Origin",
    difficulty: "Medium",
    description: "Find the k points closest to the origin.",
    topics: ["Array", "Math", "Divide and Conquer", "Sorting", "Heap"],
    url: "https://leetcode.com/problems/k-closest-points-to-origin/",
  },
  {
    id: 4,
    title: "Kth Largest Element in an Array",
    difficulty: "Medium",
    description: "Find the kth largest element in an unsorted array.",
    topics: ["Array", "Sorting", "Heap", "Divide and Conquer", "Quickselect"],
    url: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
  },
  {
    id: 5,
    title: "Task Scheduler",
    difficulty: "Medium",
    description: "Schedule CPU tasks with a cooldown to minimize total time.",
    topics: ["Array", "Hash Table", "Greedy", "Sorting", "Heap", "Counting"],
    url: "https://leetcode.com/problems/task-scheduler/",
  },
  {
    id: 6,
    title: "Design Twitter",
    difficulty: "Medium",
    description: "Design a simplified version of Twitter with posting and a news feed.",
    topics: ["Hash Table", "Design", "Heap", "Linked List"],
    url: "https://leetcode.com/problems/design-twitter/",
  },
  {
    id: 7,
    title: "Find Median from Data Stream",
    difficulty: "Hard",
    description: "Design a data structure that supports adding numbers and finding the median efficiently.",
    topics: ["Two Pointers", "Design", "Sorting", "Heap", "Data Stream"],
    url: "https://leetcode.com/problems/find-median-from-data-stream/",
  },
];

export const backtrackingProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Subsets",
    difficulty: "Medium",
    description: "Return all possible subsets of an array of distinct integers.",
    topics: ["Array", "Backtracking", "Bit Manipulation"],
    url: "https://leetcode.com/problems/subsets/",
  },
  {
    id: 2,
    title: "Combination Sum",
    difficulty: "Medium",
    description: "Find all unique combinations that sum to a target, reusing numbers.",
    topics: ["Array", "Backtracking"],
    url: "https://leetcode.com/problems/combination-sum/",
  },
  {
    id: 3,
    title: "Permutations",
    difficulty: "Medium",
    description: "Return all possible permutations of an array of distinct integers.",
    topics: ["Array", "Backtracking"],
    url: "https://leetcode.com/problems/permutations/",
  },
  {
    id: 4,
    title: "Subsets II",
    difficulty: "Medium",
    description: "Return all possible subsets of an array that may contain duplicates.",
    topics: ["Array", "Backtracking"],
    url: "https://leetcode.com/problems/subsets-ii/",
  },
  {
    id: 5,
    title: "Combination Sum II",
    difficulty: "Medium",
    description: "Find all unique combinations that sum to a target, using each number once.",
    topics: ["Array", "Backtracking"],
    url: "https://leetcode.com/problems/combination-sum-ii/",
  },
  {
    id: 6,
    title: "Word Search",
    difficulty: "Medium",
    description: "Determine whether a word can be constructed from adjacent letters in a grid.",
    topics: ["Array", "String", "Backtracking", "Matrix"],
    url: "https://leetcode.com/problems/word-search/",
  },
  {
    id: 7,
    title: "Palindrome Partitioning",
    difficulty: "Medium",
    description: "Partition a string so that every substring is a palindrome.",
    topics: ["String", "Dynamic Programming", "Backtracking"],
    url: "https://leetcode.com/problems/palindrome-partitioning/",
  },
  {
    id: 8,
    title: "N-Queens",
    difficulty: "Hard",
    description: "Place n queens on an n x n chessboard so that no two queens attack each other.",
    topics: ["Array", "Backtracking"],
    url: "https://leetcode.com/problems/n-queens/",
  },
];

export const graphProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Number of Islands",
    difficulty: "Medium",
    description: "Count the number of islands in a grid of land and water.",
    topics: ["Array", "DFS", "BFS", "Union Find", "Matrix"],
    url: "https://leetcode.com/problems/number-of-islands/",
  },
  {
    id: 2,
    title: "Clone Graph",
    difficulty: "Medium",
    description: "Create a deep copy of a connected undirected graph.",
    topics: ["Hash Table", "DFS", "BFS", "Graph"],
    url: "https://leetcode.com/problems/clone-graph/",
  },
  {
    id: 3,
    title: "Max Area of Island",
    difficulty: "Medium",
    description: "Find the maximum area of an island in a grid.",
    topics: ["Array", "DFS", "BFS", "Union Find", "Matrix"],
    url: "https://leetcode.com/problems/max-area-of-island/",
  },
  {
    id: 4,
    title: "Pacific Atlantic Water Flow",
    difficulty: "Medium",
    description: "Find cells from which water can flow to both the Pacific and Atlantic oceans.",
    topics: ["Array", "DFS", "BFS", "Matrix"],
    url: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
  },
  {
    id: 5,
    title: "Surrounded Regions",
    difficulty: "Medium",
    description: "Capture all regions of 'O's that are surrounded by 'X's.",
    topics: ["Array", "DFS", "BFS", "Union Find", "Matrix"],
    url: "https://leetcode.com/problems/surrounded-regions/",
  },
  {
    id: 6,
    title: "Rotting Oranges",
    difficulty: "Medium",
    description: "Find the minimum time until no fresh orange remains, using multi-source BFS.",
    topics: ["Array", "BFS", "Matrix"],
    url: "https://leetcode.com/problems/rotting-oranges/",
  },
  {
    id: 7,
    title: "Walls and Gates",
    difficulty: "Medium",
    description: "Fill each empty room with the distance to its nearest gate.",
    topics: ["Array", "BFS", "Matrix"],
    url: "https://leetcode.com/problems/walls-and-gates/",
  },
  {
    id: 8,
    title: "Course Schedule",
    difficulty: "Medium",
    description: "Determine whether all courses can be finished given their prerequisites.",
    topics: ["DFS", "BFS", "Graph", "Topological Sort"],
    url: "https://leetcode.com/problems/course-schedule/",
  },
  {
    id: 9,
    title: "Course Schedule II",
    difficulty: "Medium",
    description: "Return a valid order to finish all courses given their prerequisites.",
    topics: ["DFS", "BFS", "Graph", "Topological Sort"],
    url: "https://leetcode.com/problems/course-schedule-ii/",
  },
  {
    id: 10,
    title: "Redundant Connection",
    difficulty: "Medium",
    description: "Find the edge that can be removed to make a graph a tree.",
    topics: ["DFS", "BFS", "Union Find", "Graph"],
    url: "https://leetcode.com/problems/redundant-connection/",
  },
  {
    id: 11,
    title: "Number of Connected Components in an Undirected Graph",
    difficulty: "Medium",
    description: "Count the number of connected components in an undirected graph.",
    topics: ["DFS", "BFS", "Union Find", "Graph"],
    url: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
  },
  {
    id: 12,
    title: "Graph Valid Tree",
    difficulty: "Medium",
    description: "Determine whether a graph forms a valid tree.",
    topics: ["DFS", "BFS", "Union Find", "Graph"],
    url: "https://leetcode.com/problems/graph-valid-tree/",
  },
  {
    id: 13,
    title: "Word Ladder",
    difficulty: "Hard",
    description: "Find the length of the shortest transformation sequence between two words.",
    topics: ["Hash Table", "String", "BFS"],
    url: "https://leetcode.com/problems/word-ladder/",
  },
];

export const advancedGraphProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Min Cost to Connect All Points",
    difficulty: "Medium",
    description: "Find the minimum cost to connect all points using Manhattan distances.",
    topics: ["Array", "Union Find", "Graph", "Minimum Spanning Tree"],
    url: "https://leetcode.com/problems/min-cost-to-connect-all-points/",
  },
  {
    id: 2,
    title: "Network Delay Time",
    difficulty: "Medium",
    description: "Find the time for a signal to reach all nodes from a source, using Dijkstra's algorithm.",
    topics: ["Graph", "Heap", "Shortest Path"],
    url: "https://leetcode.com/problems/network-delay-time/",
  },
  {
    id: 3,
    title: "Reconstruct Itinerary",
    difficulty: "Hard",
    description: "Reconstruct a valid itinerary from a list of airline tickets.",
    topics: ["DFS", "Graph", "Eulerian Circuit"],
    url: "https://leetcode.com/problems/reconstruct-itinerary/",
  },
  {
    id: 4,
    title: "Swim in Rising Water",
    difficulty: "Hard",
    description: "Find the minimum time to swim from the top-left to bottom-right of a rising grid.",
    topics: ["Array", "Union Find", "Heap", "Matrix"],
    url: "https://leetcode.com/problems/swim-in-rising-water/",
  },
  {
    id: 5,
    title: "Alien Dictionary",
    difficulty: "Hard",
    description: "Derive the order of letters in an alien language from a sorted list of words.",
    topics: ["Array", "String", "DFS", "BFS", "Graph", "Topological Sort"],
    url: "https://leetcode.com/problems/alien-dictionary/",
  },
];

export const oneDDpProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Climbing Stairs",
    difficulty: "Easy",
    description: "Count the number of distinct ways to climb to the top of n stairs.",
    topics: ["Math", "Dynamic Programming", "Memoization"],
    url: "https://leetcode.com/problems/climbing-stairs/",
  },
  {
    id: 2,
    title: "Min Cost Climbing Stairs",
    difficulty: "Easy",
    description: "Find the minimum cost to reach the top of a staircase.",
    topics: ["Array", "Dynamic Programming"],
    url: "https://leetcode.com/problems/min-cost-climbing-stairs/",
  },
  {
    id: 3,
    title: "House Robber",
    difficulty: "Medium",
    description: "Find the maximum amount you can rob without robbing two adjacent houses.",
    topics: ["Array", "Dynamic Programming"],
    url: "https://leetcode.com/problems/house-robber/",
  },
  {
    id: 4,
    title: "House Robber II",
    difficulty: "Medium",
    description: "Find the maximum amount you can rob when houses are arranged in a circle.",
    topics: ["Array", "Dynamic Programming"],
    url: "https://leetcode.com/problems/house-robber-ii/",
  },
  {
    id: 5,
    title: "Decode Ways",
    difficulty: "Medium",
    description: "Count the number of ways to decode a string of digits into letters.",
    topics: ["String", "Dynamic Programming"],
    url: "https://leetcode.com/problems/decode-ways/",
  },
  {
    id: 6,
    title: "Coin Change",
    difficulty: "Medium",
    description: "Find the fewest number of coins needed to make up a given amount.",
    topics: ["Array", "Dynamic Programming", "BFS"],
    url: "https://leetcode.com/problems/coin-change/",
  },
  {
    id: 7,
    title: "Word Break",
    difficulty: "Medium",
    description: "Determine whether a string can be segmented into dictionary words.",
    topics: ["Array", "Hash Table", "String", "Dynamic Programming", "Trie"],
    url: "https://leetcode.com/problems/word-break/",
  },
  {
    id: 8,
    title: "Longest Increasing Subsequence",
    difficulty: "Medium",
    description: "Find the length of the longest strictly increasing subsequence.",
    topics: ["Array", "Binary Search", "Dynamic Programming"],
    url: "https://leetcode.com/problems/longest-increasing-subsequence/",
  },
  {
    id: 9,
    title: "Partition Equal Subset Sum",
    difficulty: "Medium",
    description: "Determine whether an array can be partitioned into two subsets with equal sum.",
    topics: ["Array", "Dynamic Programming"],
    url: "https://leetcode.com/problems/partition-equal-subset-sum/",
  },
];

export const intervalProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Insert Interval",
    difficulty: "Medium",
    description: "Insert a new interval into a sorted list of non-overlapping intervals, merging as needed.",
    topics: ["Array", "Interval"],
    url: "https://leetcode.com/problems/insert-interval/",
  },
  {
    id: 2,
    title: "Merge Intervals",
    difficulty: "Medium",
    description: "Merge all overlapping intervals in a list.",
    topics: ["Array", "Sorting", "Interval"],
    url: "https://leetcode.com/problems/merge-intervals/",
  },
  {
    id: 3,
    title: "Non Overlapping Intervals",
    difficulty: "Medium",
    description: "Find the minimum number of intervals to remove so the rest don't overlap.",
    topics: ["Array", "Dynamic Programming", "Greedy", "Sorting", "Interval"],
    url: "https://leetcode.com/problems/non-overlapping-intervals/",
  },
  {
    id: 4,
    title: "Meeting Rooms",
    difficulty: "Easy",
    description: "Determine whether a person can attend all given meetings.",
    topics: ["Array", "Sorting", "Interval"],
    url: "https://leetcode.com/problems/meeting-rooms/",
  },
  {
    id: 5,
    title: "Meeting Rooms II",
    difficulty: "Medium",
    description: "Find the minimum number of conference rooms required for a list of meetings.",
    topics: ["Array", "Two Pointers", "Heap", "Sorting", "Interval"],
    url: "https://leetcode.com/problems/meeting-rooms-ii/",
  },
  {
    id: 6,
    title: "Minimum Interval to Include Each Query",
    difficulty: "Hard",
    description: "Find the smallest interval that contains each query value.",
    topics: ["Array", "Heap", "Sorting", "Line Sweep"],
    url: "https://leetcode.com/problems/minimum-interval-to-include-each-query/",
  },
];

export const greedyProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Jump Game",
    difficulty: "Medium",
    description: "Determine whether you can reach the last index of an array of jump lengths.",
    topics: ["Array", "Dynamic Programming", "Greedy"],
    url: "https://leetcode.com/problems/jump-game/",
  },
  {
    id: 2,
    title: "Jump Game II",
    difficulty: "Medium",
    description: "Find the minimum number of jumps needed to reach the last index.",
    topics: ["Array", "Dynamic Programming", "Greedy"],
    url: "https://leetcode.com/problems/jump-game-ii/",
  },
  {
    id: 3,
    title: "Gas Station",
    difficulty: "Medium",
    description: "Find the starting gas station index from which you can complete a circular route.",
    topics: ["Array", "Greedy"],
    url: "https://leetcode.com/problems/gas-station/",
  },
  {
    id: 4,
    title: "Hand of Straights",
    difficulty: "Medium",
    description: "Determine whether a hand of cards can be rearranged into consecutive groups.",
    topics: ["Array", "Hash Table", "Greedy", "Sorting"],
    url: "https://leetcode.com/problems/hand-of-straights/",
  },
  {
    id: 5,
    title: "Merge Triplets to Form Target Triplet",
    difficulty: "Medium",
    description: "Determine whether a target triplet can be formed by merging given triplets.",
    topics: ["Array", "Greedy"],
    url: "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/",
  },
  {
    id: 6,
    title: "Partition Labels",
    difficulty: "Medium",
    description: "Partition a string into as many parts as possible so each letter appears in only one part.",
    topics: ["Hash Table", "String", "Two Pointers", "Greedy"],
    url: "https://leetcode.com/problems/partition-labels/",
  },
  {
    id: 7,
    title: "Valid Parenthesis String",
    difficulty: "Medium",
    description: "Determine whether a string with wildcards can form a valid parentheses sequence.",
    topics: ["String", "Dynamic Programming", "Stack", "Greedy"],
    url: "https://leetcode.com/problems/valid-parenthesis-string/",
  },
];

export const twoDDpProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Unique Paths",
    difficulty: "Medium",
    description: "Count the number of unique paths from the top-left to bottom-right of a grid.",
    topics: ["Math", "Dynamic Programming", "Combinatorics"],
    url: "https://leetcode.com/problems/unique-paths/",
  },
  {
    id: 2,
    title: "Longest Common Subsequence",
    difficulty: "Medium",
    description: "Find the length of the longest common subsequence of two strings.",
    topics: ["String", "Dynamic Programming"],
    url: "https://leetcode.com/problems/longest-common-subsequence/",
  },
  {
    id: 3,
    title: "Best Time to Buy And Sell Stock With Cooldown",
    difficulty: "Medium",
    description: "Maximize profit from stock trades with a cooldown period after selling.",
    topics: ["Array", "Dynamic Programming"],
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
  },
  {
    id: 4,
    title: "Coin Change II",
    difficulty: "Medium",
    description: "Count the number of combinations of coins that make up a given amount.",
    topics: ["Array", "Dynamic Programming"],
    url: "https://leetcode.com/problems/coin-change-ii/",
  },
  {
    id: 5,
    title: "Target Sum",
    difficulty: "Medium",
    description: "Count the number of ways to assign + and - signs to reach a target sum.",
    topics: ["Array", "Dynamic Programming", "Backtracking"],
    url: "https://leetcode.com/problems/target-sum/",
  },
  {
    id: 6,
    title: "Edit Distance",
    difficulty: "Medium",
    description: "Find the minimum number of operations to convert one string into another.",
    topics: ["String", "Dynamic Programming"],
    url: "https://leetcode.com/problems/edit-distance/",
  },
  {
    id: 7,
    title: "Interleaving String",
    difficulty: "Medium",
    description: "Determine whether a string is formed by interleaving two other strings.",
    topics: ["String", "Dynamic Programming"],
    url: "https://leetcode.com/problems/interleaving-string/",
  },
  {
    id: 8,
    title: "Longest Increasing Path in a Matrix",
    difficulty: "Hard",
    description: "Find the length of the longest increasing path in a matrix.",
    topics: ["Array", "DFS", "BFS", "Dynamic Programming", "Memoization", "Matrix", "Topological Sort"],
    url: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
  },
  {
    id: 9,
    title: "Distinct Subsequences",
    difficulty: "Hard",
    description: "Count the number of distinct subsequences of one string that equal another.",
    topics: ["String", "Dynamic Programming"],
    url: "https://leetcode.com/problems/distinct-subsequences/",
  },
  {
    id: 10,
    title: "Burst Balloons",
    difficulty: "Hard",
    description: "Maximize coins earned by bursting balloons in an optimal order.",
    topics: ["Array", "Dynamic Programming"],
    url: "https://leetcode.com/problems/burst-balloons/",
  },
  {
    id: 11,
    title: "Regular Expression Matching",
    difficulty: "Hard",
    description: "Implement regular expression matching supporting '.' and '*'.",
    topics: ["String", "Dynamic Programming", "Recursion"],
    url: "https://leetcode.com/problems/regular-expression-matching/",
  },
];

export const bitManipulationProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Single Number",
    difficulty: "Easy",
    description: "Find the number that appears once while every other number appears twice.",
    topics: ["Array", "Bit Manipulation"],
    url: "https://leetcode.com/problems/single-number/",
  },
  {
    id: 2,
    title: "Number of 1 Bits",
    difficulty: "Easy",
    description: "Count the number of set bits in an unsigned integer.",
    topics: ["Bit Manipulation", "Divide and Conquer"],
    url: "https://leetcode.com/problems/number-of-1-bits/",
  },
  {
    id: 3,
    title: "Counting Bits",
    difficulty: "Easy",
    description: "Count the number of set bits for every number from 0 to n.",
    topics: ["Dynamic Programming", "Bit Manipulation"],
    url: "https://leetcode.com/problems/counting-bits/",
  },
  {
    id: 4,
    title: "Reverse Bits",
    difficulty: "Easy",
    description: "Reverse the bits of a 32-bit unsigned integer.",
    topics: ["Divide and Conquer", "Bit Manipulation"],
    url: "https://leetcode.com/problems/reverse-bits/",
  },
  {
    id: 5,
    title: "Missing Number",
    difficulty: "Easy",
    description: "Find the missing number in an array containing n distinct numbers from 0 to n.",
    topics: ["Array", "Hash Table", "Math", "Bit Manipulation", "Sorting"],
    url: "https://leetcode.com/problems/missing-number/",
  },
  {
    id: 6,
    title: "Sum of Two Integers",
    difficulty: "Medium",
    description: "Add two integers without using the + or - operators.",
    topics: ["Math", "Bit Manipulation"],
    url: "https://leetcode.com/problems/sum-of-two-integers/",
  },
  {
    id: 7,
    title: "Reverse Integer",
    difficulty: "Medium",
    description: "Reverse the digits of a signed 32-bit integer.",
    topics: ["Math"],
    url: "https://leetcode.com/problems/reverse-integer/",
  },
];

export const mathGeometryProblems: DsaProblem[] = [
  {
    id: 1,
    title: "Happy Number",
    difficulty: "Easy",
    description: "Determine whether repeatedly summing the squares of a number's digits reaches 1.",
    topics: ["Hash Table", "Math", "Two Pointers"],
    url: "https://leetcode.com/problems/happy-number/",
  },
  {
    id: 2,
    title: "Plus One",
    difficulty: "Easy",
    description: "Add one to a large integer represented as an array of digits.",
    topics: ["Array", "Math"],
    url: "https://leetcode.com/problems/plus-one/",
  },
  {
    id: 3,
    title: "Set Matrix Zeroes",
    difficulty: "Medium",
    description: "Set an entire row and column to zero if an element is zero.",
    topics: ["Array", "Hash Table", "Matrix"],
    url: "https://leetcode.com/problems/set-matrix-zeroes/",
  },
  {
    id: 4,
    title: "Spiral Matrix",
    difficulty: "Medium",
    description: "Return all elements of a matrix in spiral order.",
    topics: ["Array", "Matrix", "Simulation"],
    url: "https://leetcode.com/problems/spiral-matrix/",
  },
  {
    id: 5,
    title: "Rotate Image",
    difficulty: "Medium",
    description: "Rotate an n x n matrix by 90 degrees in place.",
    topics: ["Array", "Math", "Matrix"],
    url: "https://leetcode.com/problems/rotate-image/",
  },
  {
    id: 6,
    title: "Pow(x, n)",
    difficulty: "Medium",
    description: "Implement power function using fast exponentiation.",
    topics: ["Math", "Recursion"],
    url: "https://leetcode.com/problems/powx-n/",
  },
  {
    id: 7,
    title: "Multiply Strings",
    difficulty: "Medium",
    description: "Multiply two numbers represented as strings without converting them to integers.",
    topics: ["Math", "String", "Simulation"],
    url: "https://leetcode.com/problems/multiply-strings/",
  },
  {
    id: 8,
    title: "Detect Squares",
    difficulty: "Medium",
    description: "Design a data structure that adds points and counts axis-aligned squares.",
    topics: ["Array", "Hash Table", "Design", "Counting"],
    url: "https://leetcode.com/problems/detect-squares/",
  },
];
